stages:
  - build
  - deploy_gcp

build_images:
  stage: build
  image: docker:20.10.16

  services:
    - docker:20.10.16-dind
  
  variables:
    DOCKER_TLS_CERTDIR: "/certs"

  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  
  script:
    - docker build -t gordelando/app-ci-cd:1.0 app/.
    - docker push gordelando/app-ci-cd:1.0

  deploy_gcp:

    stage: deploy_gcp

    before_script:
      - chmod 400 $SSH_KEY
    
    script:
        - ssh -o StrictHostKeyChecking=no -i $SSH_KEY gcp@SSH_SERVER "sudo rm -Rf ./app-ci-cd/ && sudo git clone git@gitlab.com:gordelando/app-ci-cd.git && cd app-ci-cd && sudo chmod -x ./script.sh && sudo ./script.sh"